name: PHP Pipeline

on: [
  push,
  pull_request
]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        php-versions: [ '8.1', '8.2', '8.3' ]

    name: PHP ${{ matrix.php-versions }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer files
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: composer run-script test